name: 🐛 Bug report
description: Report errors or unexpected behavior
labels: [🐛 bug]
body:
  - type: checkboxes
    attributes:
      label: 🔍 Is there already an issue for your problem?
      description: Please make sure you are not creating an already submitted <a href="https://github.com/Korozin/Python-Texture-Converter/issues">Issue</a>. Check closed issues as well, because your issue may have already been fixed.
      options:
        - label: I have checked older issues, open and closed
          required: true
  - type: textarea
    attributes:
      label: ℹ Environment / Computer Info
      description: Please provide the details of the system PyConvert is running on.
      value: |
        - PyConvert Version:
        - Operating System (OS):
      placeholder: |
        - PyConvert Version: (EX: 2023.08.18)
        - Operating System (OS): Windows / Linux
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📝 Description
      description: List steps to reproduce the error and details on what happens and what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📸 Screenshots
      description: Place any screenshots of the issue here if needed
    validations:
      required: false
