#---- 1.8 Java Data Maps ----#

Java_Items_1_8 = [
        "leather_helmet.png","chainmail_helmet.png","iron_helmet.png","diamond_helmet.png","gold_helmet.png","flint_and_steel.png","flint.png","coal.png","string.png","seeds_wheat.png","apple.png","apple_golden.png","egg.png","sugar.png","snowball.png","elytra.png",
        "leather_chestplate.png","chainmail_chestplate.png","iron_chestplate.png","diamond_chestplate.png","gold_chestplate.png","bow_standby.png","brick.png","iron_ingot.png","feather.png","wheat.png","painting.png","sugarcane.png","bone.png","cake.png","slimeball.png","broken_elytra.png",
        "leather_leggings.png","chainmail_leggings.png","iron_leggings.png","diamond_leggings.png","gold_leggings.png","arrow.png","end_crystal.png","gold_ingot.png","gunpowder.png","bread.png","sign.png","door_wood.png","door_iron.png","blank.png","fireball.png","chorus_fruit.png",
        "leather_boots.png","chainmail_boots.png","iron_boots.png","diamond_boots.png","gold_boots.png","stick.png","compass_00.png","diamond.png","redstone_dust.png","clay_ball.png","paper.png","book_normal.png","map_empty.png","seeds_pumpkin.png","seeds_melon.png","popped_chorus_fruit.png",
        "wood_sword.png","stone_sword.png","iron_sword.png","diamond_sword.png","gold_sword.png","fishing_rod_uncast.png","clock_00.png","bowl.png","mushroom_stew.png","glowstone_dust.png","bucket_empty.png","bucket_water.png","bucket_lava.png","bucket_milk.png","dye_powder_black.png","dye_powder_gray.png",
        "wood_shovel.png","stone_shovel.png","iron_shovel.png","diamond_shovel.png","gold_shovel.png","fishing_rod_cast.png","repeater.png","porkchop_raw.png","porkchop_cooked.png","fish_cod_raw.png","fish_cod_cooked.png","rotten_flesh.png","cookie.png","shears.png","dye_powder_red.png","dye_powder_pink.png",
        "wood_pickaxe.png","stone_pickaxe.png","iron_pickaxe.png","diamond_pickaxe.png","gold_pickaxe.png","bow_pulling_0.png","carrot_on_a_stick.png","leather.png","saddle.png","beef_raw.png","beef_cooked.png","ender_pearl.png","blaze_rod.png","melon.png","dye_powder_green.png","dye_powder_lime.png",
        "wood_axe.png","stone_axe.png","iron_axe.png","diamond_axe.png","gold_axe.png","bow_pulling_1.png","potato_baked.png","potato.png","carrot.png","chicken_raw.png","chicken_cooked.png","ghast_tear.png","gold_nugget.png","nether_wart.png","dye_powder_brown.png","dye_powder_yellow.png",
        "wood_hoe.png","stone_hoe.png","iron_hoe.png","diamond_hoe.png","gold_hoe.png","bow_pulling_2.png","potato_poisonous.png","minecart_normal.png","boat.png","melon_speckled.png","spider_eye_fermented.png","spider_eye.png","potion_bottle_drinkable.png","potion_overlay.png","dye_powder_blue.png","dye_powder_light_blue.png",
        "leather_helmet_overlay.png","spectral_arrow.png","iron_horse_armor.png","diamond_horse_armor.png","gold_horse_armor.png","comparator.png","carrot_golden.png","minecart_chest.png","pumpkin_pie.png","spawn_egg.png","potion_bottle_splash.png","ender_eye.png","cauldron.png","blaze_powder.png","dye_powder_purple.png","dye_powder_magenta.png",
        "blank.png","tipped_arrow_base.png","dragon_breath.png","name_tag.png","lead.png","netherbrick.png","fish_clownfish_raw.png","minecart_furnace.png","charcoal.png","spawn_egg_overlay.png","blank.png","experience_bottle.png","brewing_stand.png","magma_cream.png","dye_powder_cyan.png","dye_powder_orange.png",
        "leather_leggings_overlay.png","tipped_arrow_head.png","lingering_potion.png","barrier.png","mutton_raw.png","rabbit_raw.png","fish_pufferfish_raw.png","minecart_hopper.png","hopper.png","nether_star.png","emerald.png","book_writable.png","book_written.png","flower_pot.png","dye_powder_silver.png","dye_powder_white.png",
        "leather_boots_overlay.png","beetroot.png","beetroot_seeds.png","beetroot_soup.png","mutton_cooked.png","rabbit_cooked.png","fish_salmon_raw.png","minecart_tnt.png","armor_stand.png","fireworks.png","fireworks_charge.png","fireworks_charge_overlay.png","quartz.png","map.png","item_frame.png","book_enchanted.png",
        "door_acacia.png","door_birch.png","door_dark_oak.png","door_jungle.png","door_spruce.png","rabbit_stew.png","fish_salmon_cooked.png","minecart_command_block.png","acacia_boat.png","birch_boat.png","dark_oak_boat.png","jungle_boat.png","spruce_boat.png","prismarine_shard.png","prismarine_crystals.png","leather_horse_armor.png",
        "structure_void.png","blank.png","totem_of_undying.png","shulker_shell.png","iron_nugget.png","rabbit_foot.png","rabbit_hide.png","blank.png","blank.png","blank.png","blank.png","blank.png","blank.png","blank.png","blank.png","dragon_charge.png",
        "13.png","cat.png","blocks.png","chirp.png","far.png","mall.png","mellohi.png","stal.png","strad.png","ward.png","11.png","wait.png","cod_bucket.png","salmon_bucket.png","pufferfish_bucket.png","tropical_fish_bucket.png",
        "leather_horse_overlay.png","blank.png","blank.png","blank.png","blank.png","blank.png","blank.png","kelp.png","dried_kelp.png","sea_pickle.png","nautilus_shell.png","heart_of_the_sea.png","turtle_helmet.png","scute.png","trident.png","phantom_membrane.png"
]

Java_Blocks_1_8 = [
        "grass_top.png","stone.png","dirt.png","grass_side.png","planks_oak.png","stone_slab_side.png","stone_slab_top.png","brick.png","tnt_side.png","tnt_top.png","tnt_bottom.png","web.png","poppy.png","flower_dandelion.png","blue_concrete.png","sapling_oak.png",
        "cobblestone.png","bedrock.png","sand.png","gravel.png","log_oak.png","log_oak_top.png","iron_block.png","gold_block.png","diamond_block.png","emerald_block.png","redstone_block.png","dropper_front_horizontal.png","mushroom_red.png","mushroom_brown.png","sapling_jungle.png","red_concrete.png",
        "gold_ore.png","iron_ore.png","coal_ore.png","bookshelf.png","cobblestone_mossy.png","obsidian.png","grass_side_overlay.png","tallgrass.png","dispenser_front_vertical.png","beacon.png","dropper_front_vertical.png","crafting_table_top.png","furnace_front_off.png","furnace_side.png","dispenser_front_horizontal.png","red_concrete.png",
        "sponge.png","glass.png","diamond_ore.png","redstone_ore.png","leaves_oak.png","black_concrete.png","stonebrick.png","dead_bush.png","fern.png","daylight_detector_top.png","daylight_detector_side.png","crafting_table_side.png","crafting_table_front.png","furnace_front_on.png","furnace_top.png","sapling_spruce.png",
        "wool_colored_white.png","mob_spawner.png","snow.png","ice.png","snow.png","cactus_top.png","cactus_side.png","cactus_bottom.png","clay.png","reeds.png","jukebox_side.png","jukebox_top.png","leaves_birch.png","mycelium_side.png","mycelium_top.png","sapling_birch.png",
        "torch_on.png","door_wood_upper.png","door_iron_upper.png","ladder.png","trapdoor.png","iron_bars.png","farmland_wet.png","farmland_dry.png","wheat_stage_0.png","wheat_stage_1.png","wheat_stage_2.png","wheat_stage_3.png","wheat_stage_4.png","wheat_stage_5.png","wheat_stage_6.png","wheat_stage_7.png",
        "lever.png","door_wood_lower.png","door_iron_lower.png","redstone_torch_on.png","stonebrick_mossy.png","stonebrick_cracked.png","pumpkin_top.png","netherrack.png","soul_sand.png","glowstone.png","piston_top_sticky.png","piston_top.png","piston_side.png","piston_bottom.png","piston_inner.png","pumpkin_stem_disconnected.png",
        "rail_normal_turned.png","wool_colored_black.png","wool_colored_gray.png","redstone_torch_off.png","spruce_log.png","log_birch.png","pumpkin_side.png","pumpkin_face_off.png","pumpkin_face_on.png","cake_top.png","cake_side.png","cake_inner.png","cake_bottom.png","mushroom_block_skin_red.png","mushroom_block_skin_red.png","pumpkin_stem_connected.png","rail_normal.png","wool_colored_red.png","wool_colored_pink.png","repeater_off.png","leaves_spruce.png","leaves_spruce.png","conduit.png","turtle_egg.png","melon_side.png","melon_top.png","cauldron_top.png","cauldron_inner.png","sponge_wet.png","mushroom_block_skin_stem.png","mushroom_block_inside.png","vine.png",
        "lapis_block.png","wool_colored_green.png","wool_colored_lime.png","repeater_on.png","glass_pane_top.png","chest_top.png","ender_chest_top.png","turtle_egg_slightly_cracked.png","turtle_egg_very_cracked.png","jungle_log.png","cauldron_side.png","cauldron_bottom.png","brewing_stand_base.png","brewing_stand.png","endframe_top.png","endframe_side.png",
        "lapis_ore.png","wool_colored_brown.png","wool_colored_yellow.png","rail_golden.png","redstone_cross.png","redstone_line_horizontal.png","enchanting_table_top.png","dragon_egg.png","cocoa_stage_2.png","cocoa_stage_1.png","cocoa_stage_0.png","emerald_ore.png","trip_wire_source.png","trip_wire.png","end_portal_frame_eye.png","end_stone.png",
        "sandstone_top.png","wool_colored_blue.png","wool_colored_light_blue.png","rail_golden_powered.png","blank.png","blank.png","enchanting_table_side.png","enchanting_table_bottom.png","glide_blue.png","item_frame.png","flower_pot.png","comparator_off.png","comparator_on.png","rail_activator.png","rail_activator_powered.png","quartz_ore.png","sandstone_normal.png","wool_colored_purple.png","wool_colored_magenta.png","rail_detector.png","jungle_leaves.png","black_concrete.png","planks_spruce.png","planks_jungle.png","carrots_stage_0.png","carrots_stage_1.png","carrots_stage_2.png","carrots_stage_3.png","slime.png","water_debug.png","water_debug.png","water_debug.png","sandstone_bottom.png","wool_colored_cyan.png","wool_colored_orange.png","redstone_lamp_off.png","redstone_lamp_on.png","stonebrick_carved.png","planks_birch.png","anvil_base.png","anvil_top_damaged_1.png","quartz_block_chiseled_top.png","quartz_block_lines_top.png","quartz_block_side.png","hopper_outside.png","rail_detector_powered.png","water_debug.png","water_debug.png",
        "nether_brick.png","wool_colored_silver.png","nether_wart_stage_0.png","nether_wart_stage_1.png","nether_wart_stage_2.png","sandstone_carved.png","sandstone_smooth.png","anvil_top_damaged_0.png","anvil_top_damaged_2.png","chiseled_quartz_block_bottom.png","quartz_block_lines.png","quartz_block_top.png","hopper_inside.png","lava_debug.png","lava_debug.png","lava_debug.png",
        "destroy_stage_0.png","destroy_stage_1.png","destroy_stage_2.png","destroy_stage_3.png","destroy_stage_4.png","destroy_stage_5.png","destroy_stage_6.png","destroy_stage_7.png","destroy_stage_8.png","destroy_stage_9.png","hay_block_side.png","quartz_block_bottom.png","hopper_top.png","hay_block_top.png","lava_debug.png","lava_debug.png",
        "coal_block.png","hardened_clay.png","noteblock.png","stone_andesite.png","stone_andesite_smooth.png","stone_diorite.png","stone_diorite_smooth.png","stone_granite.png","stone_granite_smooth.png","potatoes_stage_0.png","potatoes_stage_1.png","potatoes_stage_2.png","potatoes_stage_3.png","log_spruce_top.png","log_jungle_top.png","log_birch_top.png",
        "hardened_clay_stained_black.png","hardened_clay_stained_blue.png","hardened_clay_stained_brown.png","hardened_clay_stained_cyan.png","hardened_clay_stained_gray.png","hardened_clay_stained_green.png","hardened_clay_stained_light_blue.png","hardened_clay_stained_lime.png","hardened_clay_stained_magenta.png","hardened_clay_stained_orange.png","hardened_clay_stained_pink.png","hardened_clay_stained_purple.png","hardened_clay_stained_red.png","hardened_clay_stained_silver.png","hardened_clay_stained_white.png","hardened_clay_stained_yellow.png",
        "glass_black.png","glass_blue.png","glass_brown.png","glass_cyan.png","glass_gray.png","glass_green.png","glass_light_blue.png","glass_lime.png","glass_magenta.png","glass_orange.png","glass_pink.png","glass_purple.png","glass_red.png","glass_silver.png","glass_white.png","glass_yellow.png",
        "glass_pane_top_black.png","glass_pane_top_blue.png","glass_pane_top_brown.png","glass_pane_top_cyan.png","glass_pane_top_gray.png","glass_pane_top_green.png","glass_pane_top_light_blue.png","glass_pane_top_lime.png","glass_pane_top_magenta.png","glass_pane_top_orange.png","glass_pane_top_pink.png","glass_pane_top_purple.png","glass_pane_top_red.png","glass_pane_top_silver.png","glass_pane_top_white.png","glass_pane_top_yellow.png",
        "double_plant_fern_top.png","double_plant_grass_top.png","double_plant_paeonia_top.png","double_plant_rose_top.png","double_plant_syringa_top.png","flower_tulip_orange.png","double_plant_sunflower_top.png","double_plant_sunflower_front.png","acacia_log.png","acacia_log_top.png","planks_acacia.png","leaves_acacia.png","leaves_acacia.png","prismarine_bricks.png","red_sand.png","red_sandstone_top.png",
        "double_plant_fern_bottom.png","double_plant_grass_bottom.png","double_plant_paeonia_bottom.png","double_plant_rose_bottom.png","double_plant_syringa_bottom.png","flower_tulip_pink.png","double_plant_sunflower_bottom.png","double_plant_sunflower_bottom.png","dark_oak_log.png","dark_oak_log_top.png","planks_big_oak.png","leaves_big_oak.png","leaves_big_oak.png","dark_prismarine.png","red_sandstone_bottom.png","red_sandstone_normal.png",
        "flower_allium.png","flower_blue_orchid.png","flower_houstonia.png","flower_oxeye_daisy.png","flower_tulip_red.png","flower_tulip_white.png","sapling_acacia.png","sapling_roofed_oak.png","coarse_dirt.png","dirt_podzol_side.png","dirt_podzol_top.png","leaves_spruce.png","leaves_spruce.png","rough_prismarine.png","red_sandstone_carved.png","red_sandstone_smooth.png",
        "door_acacia_upper.png","door_birch_upper.png","door_dark_oak_upper.png","door_jungle_upper.png","door_spruce_upper.png","chorus_flower.png","chorus_flower_dead.png","chorus_plant.png","end_stone_bricks.png","grass_path_side.png","grass_path_top.png","barrier.png","ice_packed.png","sea_lantern.png","daylight_detector_inverted_top.png","iron_trapdoor.png",
        "door_acacia_lower.png","door_birch_lower.png","door_dark_oak_lower.png","door_jungle_lower.png","door_spruce_lower.png","purpur_block.png","purpur_pillar.png","purpur_pillar_top.png","end_rod.png","magma.png","nether_wart_block.png","red_nether_bricks.png","frosted_ice_0.png","frosted_ice_1.png","frosted_ice_2.png","frosted_ice_3.png",
        "beetroots_stage_0.png","beetroots_stage_1.png","beetroots_stage_2.png","beetroots_stage_3.png","green_cmd.png","green_cmd.png","green_cmd.png","green_cmd.png","cmd.png","cmd.png","cmd.png","cmd.png","purple_cmd.png","purple_cmd.png","purple_cmd.png","purple_cmd.png",
        "bone_block_side.png","bone_block_top.png","melon_stem_disconnected.png","melon_stem_connected.png","observer_front.png","observer_side.png","observer_back.png","observer_back_on.png","observer_top.png","glide_yellow.png","glide_green.png","structure_block.png","structure_block_corner.png","structure_block_data.png","structure_block_load.png","structure_block_save.png",
        "black_concrete.png","blue_concrete.png","brown_concrete.png","cyan_concrete.png","gray_concrete.png","green_concrete.png","light_blue_concrete.png","lime_concrete.png","magenta_concrete.png","orange_concrete.png","pink_concrete.png","purple_concrete.png","red_concrete.png","light_gray_concrete.png","white_concrete.png","yellow_concrete.png",
        "black_concrete_powder.png","blue_concrete_powder.png","brown_concrete_powder.png","cyan_concrete_powder.png","gray_concrete_powder.png","green_concrete_powder.png","light_blue_concrete_powder.png","lime_concrete_powder.png","magenta_concrete_powder.png","orange_concrete_powder.png","pink_concrete_powder.png","purple_concrete_powder.png","red_concrete_powder.png","light_gray_concrete_powder.png","white_concrete_powder.png","yellow_concrete_powder.png",
        "black_glazed_terracotta.png","blue_glazed_terracotta.png","brown_glazed_terracotta.png","cyan_glazed_terracotta.png","gray_glazed_terracotta.png","green_glazed_terracotta.png","light_blue_glazed_terracotta.png","lime_glazed_terracotta.png","magenta_glazed_terracotta.png","orange_glazed_terracotta.png","pink_glazed_terracotta.png","purple_glazed_terracotta.png","red_glazed_terracotta.png","light_gray_glazed_terracotta.png","white_glazed_terracotta.png","yellow_glazed_terracotta.png",
        "white_shulker_box.png","blank.png","water_overlay.png","tall_seagrass_top.png","tube_coral_block.png","bubble_coral_block.png","brain_coral_block.png","fire_coral_block.png","horn_coral_block.png","tube_coral.png","bubble_coral.png","brain_coral.png","fire_coral.png","horn_coral.png","sea_pickle.png","blue_ice.png",
        "dried_kelp_top.png","dried_kelp_side.png","seagrass.png","tall_seagrass_bottom.png","dead_tube_coral_block.png","dead_bubble_coral_block.png","dead_brain_coral_block.png","dead_fire_coral_block.png","dead_horn_coral_block.png","tube_coral_fan.png","bubble_coral_fan.png","brain_coral_fan.png","fire_coral_fan.png","horn_coral_fan.png","blank.png","blank.png",
        "large_kelp_bottom.png","large_kelp_bottom.png","large_kelp_bottom.png","large_kelp_bottom.png","large_kelp_top.png","large_kelp_top.png","large_kelp_top.png","large_kelp_top.png","seagrass_2.png","dead_tube_coral_fan.png","dead_bubble_coral_fan.png","dead_brain_coral_fan.png","dead_fire_coral_fan.png","dead_horn_coral_fan.png","blank.png","spruce_trapdoor.png",
        "stripped_oak_log.png","stripped_oak_log_top.png","stripped_acacia_log.png","stripped_acacia_log_top.png","stripped_birch_log.png","stripped_birch_log_top.png","stripped_dark_oak_log.png","stripped_dark_oak_log_top.png","stripped_jungle_log.png","stripped_jungle_log_top.png","stripped_spruce_log.png","stripped_spruce_log_top.png","acacia_trapdoor.png","birch_trapdoor.png","dark_oak_trapdoor.png","jungle_trapdoor.png"
]

Java_Armor = {
        'chainmail_layer_1.png': 'chain_1.png',
        'chainmail_layer_2.png': 'chain_2.png',
        'diamond_layer_1.png': 'diamond_1.png',
        'diamond_layer_2.png': 'diamond_2.png',
        'gold_layer_1.png': 'gold_1.png',
        'gold_layer_2.png': 'gold_2.png',
        'iron_layer_1.png': 'iron_1.png',
        'iron_layer_2.png': 'iron_2.png',
        'leather_layer_1.png': 'cloth_1.png',
        'leather_layer_2.png': 'cloth_2.png',
        'leather_layer_1_overlay.png': 'cloth_1_b.png',
        'leather_layer_2_overlay.png': 'cloth_2_b.png'
}

Java_Fire_1_8 = {
        'fire_layer_0.png': 'fire_0.png',
        'fire_layer_1.png': 'fire_1.png',
}

Java_Particles = {
        'particles.png': 'particles.png'
}

Java_Environment = {
        'clouds.png': 'clouds.png',
        'end_sky.png': 'end_sky.png',
        'moon_phases.png': 'moon_phases.png',
        'rain.png': 'rain.png',
        'snow.png': 'snow.png',
        'sun.png': 'sun.png'
}

Java_Misc = {
        'enchanted_item_glint.png': 'glint.png',
        'pumpkinblur.png': 'pumpkinblur.png',
        'shadow.png': 'shadow.png'
}

#---- 1.13+ Java Data Maps ----#

Java_Items_1_13 = [
        "leather_helmet.png","chainmail_helmet.png","iron_helmet.png","diamond_helmet.png","golden_helmet.png","flint_and_steel.png","flint.png","coal.png","string.png","wheat_seeds.png","apple.png","golden_apple.png","egg.png","sugar.png","snowball.png","elytra.png",
        "leather_chestplate.png","chainmail_chestplate.png","iron_chestplate.png","diamond_chestplate.png","golden_chestplate.png","bow.png","brick.png","iron_ingot.png","feather.png","wheat.png","painting.png","sugarcane.png","bone.png","cake.png","slime_ball.png","broken_elytra.png",
        "leather_leggings.png","chainmail_leggings.png","iron_leggings.png","diamond_leggings.png","golden_leggings.png","arrow.png","end_crystal.png","gold_ingot.png","gunpowder.png","bread.png","oak_sign.png","oak_door.png","iron_door.png","blank.png.png","fire_charge.png","chorus_fruit.png",
        "leather_boots.png","chainmail_boots.png","iron_boots.png","diamond_boots.png","golden_boots.png","stick.png","compass_00.png","diamond.png","redstone.png","clay_ball.png","paper.png","book.png","map.png","pumpkin_seeds.png","melon_seeds.png","popped_chorus_fruit.png",
        "wooden_sword.png","stone_sword.png","iron_sword.png","diamond_sword.png","golden_sword.png","fishing_rod.png","clock_00.png","bowl.png","mushroom_stew.png","glowstone_dust.png","bucket.png","water_bucket.png","lava_bucket.png","milk_bucket.png","ink_sac.png","gray_dye.png",
        "wooden_shovel.png","stone_shovel.png","iron_shovel.png","diamond_shovel.png","golden_shovel.png","fishing_rod_cast.png","repeater.png","porkchop.png","cooked_porkchop.png","cod.png","cooked_cod.png","rotten_flesh.png","cookie.png","shears.png","red_dye.png","pink_dye.png",
        "wooden_pickaxe.png","stone_pickaxe.png","iron_pickaxe.png","diamond_pickaxe.png","golden_pickaxe.png","bow_pulling_0.png","carrot_on_a_stick.png","leather.png","saddle.png","beef.png","cooked_beef.png","ender_pearl.png","blaze_rod.png","melon_slice.png","green_dye.png","lime_dye.png",
        "wooden_axe.png","stone_axe.png","iron_axe.png","diamond_axe.png","golden_axe.png","bow_pulling_1.png","baked_potato.png","potato.png","carrot.png","chicken.png","cooked_chicken.png","ghast_tear.png","gold_nugget.png","nether_wart.png","cocoa_beans.png","yellow_dye.png",
        "wooden_hoe.png","stone_hoe.png","iron_hoe.png","diamond_hoe.png","golden_hoe.png","bow_pulling_2.png","poisonous_potato.png","minecart.png","oak_boat.png","glistering_melon_slice.png","fermented_spider_eye.png","spider_eye.png","potion.png","potion_overlay.png","blue_dye.png","light_blue_dye.png",
        "leather_helmet_overlay.png","spectral_arrow.png","iron_horse_armor.png","diamond_horse_armor.png","golden_horse_armor.png","comparator.png","golden_carrot.png","chest_minecart.png","pumpkin_pie.png","spawn_egg.png","splash_potion.png","ender_eye.png","cauldron.png","blaze_powder.png","purple_dye.png","magenta_dye.png",
        "blank.png.png","tipped_arrow_base.png","dragon_breath.png","name_tag.png","lead.png","nether_brick.png","tropical_fish.png","furnace_minecart.png","charcoal.png","spawn_egg_overlay.png","blank.png.png","experience_bottle.png","brewing_stand.png","magma_cream.png","cyan_dye.png","orange_dye.png",
        "leather_leggings_overlay.png","tipped_arrow_head.png","lingering_potion.png","barrier.png","mutton.png","rabbit.png","pufferfish.png","hopper_minecart.png","hopper.png","nether_star.png","emerald.png","writable_book.png","written_book.png","flower_pot.png","light_gray_dye.png","bone_meal.png",
        "leather_boots_overlay.png","beetroot.png","beetroot_seeds.png","beetroot_soup.png","cooked_mutton.png","cooked_rabbit.png","salmon.png","tnt_minecart.png","armor_stand.png","firework_rocket.png","firework_star.png","firework_star_overlay.png","quartz.png","map.png","item_frame.png","enchanted_book.png",
        "acacia_door.png","birch_door.png","dark_oak_door.png","jungle_door.png","spruce_door.png","rabbit_stew.png","cooked_salmon.png","command_block_minecart.png","acacia_boat.png","birch_boat.png","dark_oak_boat.png","jungle_boat.png","spruce_boat.png","prismarine_shard.png","prismarine_crystals.png","leather_horse_armor.png",
        "structure_void.png","blank.png.png","totem_of_undying.png","shulker_shell.png","iron_nugget.png","rabbit_foot.png","rabbit_hide.png","blank.png.png","blank.png.png","blank.png.png","blank.png.png","blank.png.png","blank.png.png","blank.png.png","blank.png.png","blank.png.png",
        "music_disc_13.png","music_disc_cat.png","music_disc_blocks.png","music_disc_chirp.png","music_disc_far.png","music_disc_mall.png","music_disc_mellohi.png","music_disc_stal.png","music_disc_strad.png","music_disc_ward.png","music_disc_11.png","music_disc_wait.png","cod_bucket.png","salmon_bucket.png","pufferfish_bucket.png","tropical_fish_bucket.png",
        "leather_horse_armor.png","blank.png.png","blank.png.png","blank.png.png","blank.png.png","blank.png.png","blank.png.png","kelp.png","dried_kelp.png","sea_pickle.png","nautilus_shell.png","heart_of_the_sea.png","turtle_helmet.png","scute.png","trident.png","phantom_membrane.png"
]

Java_Blocks_1_13 = [
        "grass_block_top.png","stone.png","dirt.png","grass_block_side.png","oak_planks.png","smooth_stone_slab_side.png","smooth_stone.png","bricks.png","tnt_side.png","tnt_top.png","tnt_bottom.png","cobweb.png","poppy.png","dandelion.png","blue_concrete.png","oak_sapling.png",
        "cobblestone.png","bedrock.png","sand.png","gravel.png","oak_log.png","oak_log_top.png","iron_block.png","gold_block.png","diamond_block.png","emerald_block.png","redstone_block.png","dropper_front.png","red_mushroom.png","brown_mushroom.png","jungle_sapling.png","red_concrete.png",
        "gold_ore.png","iron_ore.png","coal_ore.png","bookshelf.png","mossy_cobblestone.png","obsidian.png","grass_block_side_overlay.png","grass.png","dispenser_front_vertical.png","beacon.png","dropper_front_vertical.png","crafting_table_top.png","furnace_front.png","furnace_side.png","dispenser_front.png","red_concrete.png",
        "sponge.png","glass.png","diamond_ore.png","redstone_ore.png","oak_leaves.png","black_concrete.png","stone_bricks.png","dead_bush.png","fern.png","daylight_detector_top.png","daylight_detector_side.png","crafting_table_side.png","crafting_table_front.png","furnace_front_on.png","furnace_top.png","spruce_sapling.png",
        "white_wool.png","spawner.png","snow.png","ice.png","grass_block_snow.png","cactus_top.png","cactus_side.png","cactus_bottom.png","clay.png","sugar_cane.png","jukebox_side.png","jukebox_top.png","birch_leaves.png","mycelium_side.png","mycelium_top.png","birch_sapling.png",
        "torch.png","oak_door_top.png","iron_door_top.png","ladder.png","oak_trapdoor.png","iron_bars.png","farmland_wet.png","farmland.png","wheat_stage0.png","wheat_stage1.png","wheat_stage2.png","wheat_stage3.png","wheat_stage4.png","wheat_stage5.png","wheat_stage6.png","wheat_stage7.png",
        "lever.png","oak_door_bottom.png","iron_door_bottom.png","redstone_torch.png","mossy_stone_bricks.png","cracked_stone_bricks.png","pumpkin_top.png","netherrack.png","soul_sand.png","glowstone.png","piston_top_sticky.png","piston_top.png","piston_side.png","piston_bottom.png","piston_inner.png","pumpkin_stem.png",
        "rail_corner.png","black_wool.png","gray_wool.png","redstone_torch_off.png","spruce_log.png","birch_log.png","pumpkin_side.png","carved_pumpkin.png","jack_o_lantern.png","cake_top.png","cake_side.png","cake_inner.png","cake_bottom.png","red_mushroom_block.png","brown_mushroom_block.png","attached_pumpkin_stem.png",
        "rail.png","red_wool.png", "pink_wool.png","repeater.png","spruce_leaves.png","spruce_leaves.png","conduit.png","turtle_egg.png","melon_side.png","melon_top.png","cauldron_top.png","cauldron_inner.png","wet_sponge.png","mushroom_stem.png","mushroom_block_inside.png","vines.png",
        "lapis_block.png","green_wool.png","lime_wool.png","repeater_on.png","glass_pane_top.png","chest_top.png","ender_chest_top.png","turtle_egg_slightly_cracked.png","turtle_egg_very_cracked.png","jungle_log.png","cauldron_side.png","cauldron_bottom.png","brewing_stand_base.png","brewing_stand.png","end_portal_frame_top.png","end_portal_frame_side.png",
        "lapis_ore.png","brown_wool.png","yellow_wool.png","powered_rail.png","redstone_dust_dot.png","redstone_dust_line0.png","enchanting_table_top.png","dragon_egg.png","cocoa_stage2.png","cocoa_stage1.png","cocoa_stage0.png","emerald_ore.png","tripwire_hook.png","tripwire.png","end_portal_frame_eye.png","end_stone.png",
        "sandstone_top.png","blue_wool.png","light_blue_wool.png","powered_rail_on.png","blank.png","blank.png","enchanting_table_side.png","enchanting_table_bottom.png","glide_blue.png","item_frame.png","flower_pot.png","comparator.png","comparator_on.png","activator_rail.png","activator_rail.png","nether_quartz_ore.png",
        "sandstone.png","purple_wool.png","magenta_wool.png","detector_rail.png","jungle_leaves.png","black_concrete.png","spruce_planks.png","jungle_planks.png","carrots_stage0.png","carrots_stage1.png","carrots_stage2.png","carrots_stage3.png","slime_block.png","water_debug.png","water_debug.png","water_debug.png",
        "sandstone_bottom.png","cyan_wool.png","orange_wool.png","redstone_lamp.png","redstone_lamp_on.png","chiseled_stone_bricks.png","birch_planks.png","anvil.png","chipped_anvil_top.png","chiseled_quartz_block_top.png","quartz_pillar_top.png","quartz_block_side.png","hopper_outside.png","detector_rail_on.png","water_debug.png","water_debug.png",
        "nether_bricks.png","light_gray_wool.png","nether_wart_stage0.png","nether_wart_stage1.png","nether_wart_stage2.png","chiseled_sandstone.png","cut_sandstone.png","anvil_top.png","damaged_anvil_top.png","chiseled_quartz_block.png","quartz_pillar.png","quartz_block_top.png","hopper_inside.png","lava_debug.png","lava_debug.png","lava_debug.png",
        "destroy_stage_0.png","destroy_stage_1.png","destroy_stage_2.png","destroy_stage_3.png","destroy_stage_4.png","destroy_stage_5.png","destroy_stage_6.png","destroy_stage_7.png","destroy_stage_8.png","destroy_stage_9.png","hay_block_side.png","quartz_block_bottom.png","hopper_top.png","hay_block_top.png","lava_debug.png","lava_debug.png",
        "coal_block.png","terracotta.png","note_block.png","andesite.png","polished_andesite.png","diorite.png","polished_diorite.png","granite.png","polished_granite.png","potatoes_stage0.png","potatoes_stage1.png","potatoes_stage2.png","potatoes_stage3.png","spruce_log_top.png","jungle_log_top.png","birch_log_top.png",
        "black_terracotta.png","blue_terracotta.png","brown_terracotta.png","cyan_terracotta.png","gray_terracotta.png","green_terracotta.png","light_blue_terracotta.png","lime_terracotta.png","magenta_terracotta.png","orange_terracotta.png","pink_terracotta.png","purple_terracotta.png","red_terracotta.png","light_gray_terracotta.png","white_terracotta.png","yellow_terracotta.png",
        "black_stained_glass.png","blue_stained_glass.png","brown_stained_glass.png","cyan_stained_glass.png","gray_stained_glass.png","green_stained_glass.png","light_blue_stained_glass.png","lime_stained_glass.png","magenta_stained_glass.png","orange_stained_glass.png","pink_stained_glass.png","purple_stained_glass.png","red_stained_glass.png","light_gray_stained_glass.png","white_stained_glass.png","yellow_stained_glass.png",
        "black_stained_glass_pane_top.png","blue_stained_glass_pane_top.png","brown_stained_glass_pane_top.png","cyan_stained_glass_pane_top.png","gray_stained_glass_pane_top.png","green_stained_glass_pane_top.png","light_blue_stained_glass_pane_top.png","lime_stained_glass_pane_top.png","magenta_stained_glass_pane_top.png","orange_stained_glass_pane_top.png","pink_stained_glass_pane_top.png","purple_stained_glass_pane_top.png","red_stained_glass_pane_top.png","light_gray_stained_glass_pane_top.png","white_stained_glass_pane_top.png","yellow_stained_glass_pane_top.png",
        "large_fern_top.png","tall_grass_top.png","peony_top.png","rose_bush_top.png","lilac_top.png","orange_tulip.png","sunflower_top.png","sunflower_front.png","acacia_log.png","acacia_log_top.png","acacia_planks.png","acacia_leaves.png","acacia_leaves.png","prismarine_bricks.png","red_sand.png","red_sandstone_top.png",
        "large_fern_bottom.png","tall_grass_bottom.png","peony_bottom.png","rose_bush_bottom.png","lilac_bottom.png","pink_tulip.png","sunflower_bottom.png","sunflower_back.png","dark_oak_log.png","dark_oak_log_top.png","dark_oak_planks.png","dark_oak_leaves.png","dark_oak_leaves.png","dark_prismarine.png","red_sandstone_bottom.png","red_sandstone.png",
        "allium.png","blue_orchid.png","azure_bluet.png","oxeye_daisy.png","red_tulip.png","white_tulip.png","acacia_sapling.png","dark_oak_sapling.png","coarse_dirt.png","podzol_side.png","podzol_top.png","spruce_leaves.png","spruce_leaves.png","rough_prismarine.png","chiseled_red_sandstone.png","cut_red_sandstone.png",
        "acacia_door_top.png","birch_door_top.png","dark_oak_door_top.png","jungle_door_top.png","spruce_door_top.png","chorus_flower.png","chorus_flower_dead.png","chorus_plant.png","end_stone_bricks.png","grass_path_side.png","grass_path_top.png","barrier.png","packed_ice.png","sea_lantern.png","daylight_detector_inverted_top.png","iron_trapdoor.png",
        "acacia_door_bottom.png","birch_door_bottom.png","dark_oak_door_bottom.png","jungle_door_bottom.png","spruce_door_bottom.png","purpur_block.png","purpur_pillar.png","purpur_pillar_top.png","end_rod.png","magma.png","nether_wart_block.png","red_nether_bricks.png","frosted_ice_0.png","frosted_ice_1.png","frosted_ice_2.png","frosted_ice_3.png",
        "beetroots_stage0.png","beetroots_stage1.png","beetroots_stage2.png","beetroots_stage3.png","green_cmd.png","green_cmd.png","green_cmd.png","green_cmd.png","cmd.png","cmd.png","cmd.png","cmd.png","purple_cmd.png","purple_cmd.png","purple_cmd.png","purple_cmd.png",
        "bone_block_side.png","bone_block_top.png","melon_stem.png","attached_melon_stem.png","observer_front.png","observer_side.png","observer_back.png","observer_back_on.png","observer_top.png","glide_yellow.png","glide_green.png","structure_block.png","structure_block_corner.png","structure_block_data.png","structure_block_load.png","structure_block_save.png",
        "black_concrete.png","blue_concrete.png","brown_concrete.png","cyan_concrete.png","gray_concrete.png","green_concrete.png","light_blue_concrete.png","lime_concrete.png","magenta_concrete.png","orange_concrete.png","pink_concrete.png","purple_concrete.png","red_concrete.png","light_gray_concrete.png","white_concrete.png","yellow_concrete.png",
        "black_concrete_powder.png","blue_concrete_powder.png","brown_concrete_powder.png","cyan_concrete_powder.png","gray_concrete_powder.png","green_concrete_powder.png","light_blue_concrete_powder.png","lime_concrete_powder.png","magenta_concrete_powder.png","orange_concrete_powder.png","pink_concrete_powder.png","purple_concrete_powder.png","red_concrete_powder.png","light_gray_concrete_powder.png","white_concrete_powder.png","yellow_concrete_powder.png",
        "black_glazed_terracotta.png","blue_glazed_terracotta.png","brown_glazed_terracotta.png","cyan_glazed_terracotta.png","gray_glazed_terracotta.png","green_glazed_terracotta.png","light_blue_glazed_terracotta.png","lime_glazed_terracotta.png","magenta_glazed_terracotta.png","orange_glazed_terracotta.png","pink_glazed_terracotta.png","purple_glazed_terracotta.png","red_glazed_terracotta.png","light_gray_glazed_terracotta.png","white_glazed_terracotta.png","yellow_glazed_terracotta.png",
        "white_shulker_box.png","blank.png","water_overlay.png","tall_seagrass_top.png","tube_coral_block.png","bubble_coral_block.png","brain_coral_block.png","fire_coral_block.png","horn_coral_block.png","tube_coral.png","bubble_coral.png","brain_coral.png","fire_coral.png","horn_coral.png","sea_pickle.png","blue_ice.png",
        "dried_kelp_top.png","dried_kelp_side.png","seagrass.png","tall_seagrass_bottom.png","dead_tube_coral_block.png","dead_bubble_coral_block.png","dead_brain_coral_block.png","dead_fire_coral_block.png","dead_horn_coral_block.png","tube_coral_fan.png","bubble_coral_fan.png","brain_coral_fan.png","fire_coral_fan.png","horn_coral_fan.png","blank.png","blank.png.png",
        "large_kelp_bottom.png","large_kelp_bottom.png","large_kelp_bottom.png","large_kelp_bottom.png","large_kelp_top.png","large_kelp_top.png","large_kelp_top.png","large_kelp_top.png","seagrass_2.png","dead_tube_coral_fan.png","dead_bubble_coral_fan.png","dead_brain_coral_fan.png","dead_fire_coral_fan.png","dead_horn_coral_fan.png","blank.png","spruce_trapdoor.png",
        "stripped_oak_log.png","stripped_oak_log_top.png","stripped_acacia_log.png","stripped_acacia_log_top.png","stripped_birch_log.png","stripped_birch_log_top.png","stripped_dark_oak_log.png","stripped_dark_oak_log_top.png","stripped_jungle_log.png","stripped_jungle_log_top.png","stripped_spruce_log.png","stripped_spruce_log_top.png","acacia_trapdoor.png","birch_trapdoor.png","dark_oak_trapdoor.png","jungle_trapdoor.png"
]

Java_Fire_1_13 = {
        'fire_0.png': 'fire_0.png',
        'fire_1.png': 'fire_1.png',
}
