from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(493, 430)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 471, 411))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.MainTab = QtWidgets.QWidget()
        self.MainTab.setObjectName("MainTab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.MainTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 441, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Input_groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.Input_groupBox.setObjectName("Input_groupBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.Input_groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 67, 421, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Input_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.Input_lineEdit.setClearButtonEnabled(True)
        self.Input_lineEdit.setObjectName("Input_lineEdit")
        self.horizontalLayout_3.addWidget(self.Input_lineEdit)
        self.Browse_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Browse_pushButton.setObjectName("Browse_pushButton")
        self.horizontalLayout_3.addWidget(self.Browse_pushButton)
        self.horizontalLayout.addWidget(self.Input_groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Output_groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.Output_groupBox.setObjectName("Output_groupBox")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Output_groupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 65, 421, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Output_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.Output_lineEdit.setClearButtonEnabled(True)
        self.Output_lineEdit.setObjectName("Output_lineEdit")
        self.horizontalLayout_4.addWidget(self.Output_lineEdit)
        self.Browse_pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Browse_pushButton_2.setObjectName("Browse_pushButton_2")
        self.horizontalLayout_4.addWidget(self.Browse_pushButton_2)
        self.horizontalLayout_2.addWidget(self.Output_groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.Start_pushButton = QtWidgets.QPushButton(self.MainTab)
        self.Start_pushButton.setGeometry(QtCore.QRect(10, 340, 439, 25))
        self.Start_pushButton.setObjectName("Start_pushButton")
        self.tabWidget.addTab(self.MainTab, "")
        self.SettingsTab = QtWidgets.QWidget()
        self.SettingsTab.setObjectName("SettingsTab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.SettingsTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 451, 361))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Fallback_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Fallback_checkBox.setChecked(True)
        self.Fallback_checkBox.setObjectName("Fallback_checkBox")
        self.horizontalLayout_7.addWidget(self.Fallback_checkBox)
        self.Items_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Items_checkBox.setChecked(True)
        self.Items_checkBox.setObjectName("Items_checkBox")
        self.horizontalLayout_7.addWidget(self.Items_checkBox)
        self.Blocks_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Blocks_checkBox.setChecked(True)
        self.Blocks_checkBox.setObjectName("Blocks_checkBox")
        self.horizontalLayout_7.addWidget(self.Blocks_checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Armor_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Armor_checkBox.setChecked(True)
        self.Armor_checkBox.setObjectName("Armor_checkBox")
        self.horizontalLayout_8.addWidget(self.Armor_checkBox)
        self.Fire_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Fire_checkBox.setChecked(True)
        self.Fire_checkBox.setObjectName("Fire_checkBox")
        self.horizontalLayout_8.addWidget(self.Fire_checkBox)
        self.Particles_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Particles_checkBox.setChecked(True)
        self.Particles_checkBox.setObjectName("Particles_checkBox")
        self.horizontalLayout_8.addWidget(self.Particles_checkBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Misc_checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.Misc_checkBox.setChecked(True)
        self.Misc_checkBox.setObjectName("Misc_checkBox")
        self.horizontalLayout_9.addWidget(self.Misc_checkBox)
        self.Check_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Check_pushButton.sizePolicy().hasHeightForWidth())
        self.Check_pushButton.setSizePolicy(sizePolicy)
        self.Check_pushButton.setObjectName("Check_pushButton")
        self.horizontalLayout_9.addWidget(self.Check_pushButton)
        self.Uncheck_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Uncheck_pushButton.sizePolicy().hasHeightForWidth())
        self.Uncheck_pushButton.setSizePolicy(sizePolicy)
        self.Uncheck_pushButton.setObjectName("Uncheck_pushButton")
        self.horizontalLayout_9.addWidget(self.Uncheck_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.ItemsRes_groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.ItemsRes_groupBox.setObjectName("ItemsRes_groupBox")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.ItemsRes_groupBox)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 30, 201, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.ItemsRes_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_9)
        self.ItemsRes_comboBox.setObjectName("ItemsRes_comboBox")
        self.horizontalLayout_19.addWidget(self.ItemsRes_comboBox)
        self.horizontalLayout_18.addWidget(self.ItemsRes_groupBox)
        self.TerrainRes_groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.TerrainRes_groupBox.setObjectName("TerrainRes_groupBox")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.TerrainRes_groupBox)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 30, 201, 41))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.BlocksRes_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_12)
        self.BlocksRes_comboBox.setObjectName("BlocksRes_comboBox")
        self.horizontalLayout_20.addWidget(self.BlocksRes_comboBox)
        self.horizontalLayout_18.addWidget(self.TerrainRes_groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.Version_groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.Version_groupBox.setObjectName("Version_groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Version_groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 431, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Version_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.Version_comboBox.setObjectName("Version_comboBox")
        self.horizontalLayout_5.addWidget(self.Version_comboBox)
        self.verticalLayout_3.addWidget(self.Version_groupBox)
        self.Fallback_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Fallback_pushButton.setObjectName("Fallback_pushButton")
        self.verticalLayout_3.addWidget(self.Fallback_pushButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.Fallback_Label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Fallback_Label.setObjectName("Fallback_Label")
        self.horizontalLayout_6.addWidget(self.Fallback_Label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.SettingsTab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyConvert-GUI"))
        self.Input_groupBox.setTitle(_translate("MainWindow", "Input Directory"))
        self.Input_lineEdit.setPlaceholderText(_translate("MainWindow", "Input File Path Here"))
        self.Browse_pushButton.setText(_translate("MainWindow", "Browse"))
        self.Output_groupBox.setTitle(_translate("MainWindow", "Output Directory"))
        self.Output_lineEdit.setPlaceholderText(_translate("MainWindow", "Output File Path Here"))
        self.Browse_pushButton_2.setText(_translate("MainWindow", "Browse"))
        self.Start_pushButton.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainTab), _translate("MainWindow", "Main"))
        self.Fallback_checkBox.setText(_translate("MainWindow", "Use Fallback"))
        self.Items_checkBox.setText(_translate("MainWindow", "Convert Items"))
        self.Blocks_checkBox.setText(_translate("MainWindow", "Convert Blocks"))
        self.Armor_checkBox.setText(_translate("MainWindow", "Convert Armor"))
        self.Fire_checkBox.setText(_translate("MainWindow", "Convert Fire"))
        self.Particles_checkBox.setText(_translate("MainWindow", "Convert Particles"))
        self.Misc_checkBox.setText(_translate("MainWindow", "Convert Misc"))
        self.Check_pushButton.setText(_translate("MainWindow", "Check All"))
        self.Uncheck_pushButton.setText(_translate("MainWindow", "Uncheck All"))
        self.ItemsRes_groupBox.setTitle(_translate("MainWindow", "Items Res"))
        self.TerrainRes_groupBox.setTitle(_translate("MainWindow", "Terrain Res"))
        self.Version_groupBox.setTitle(_translate("MainWindow", "Version"))
        self.Fallback_pushButton.setText(_translate("MainWindow", "Download Fallback"))
        self.Fallback_Label.setText(_translate("MainWindow", "<html><head/><body><p>fallback : <span style=\" color:#ff0000;\">missing</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SettingsTab), _translate("MainWindow", "Settings"))
