name: Build binaries for Linux & Windows
on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          ./bin/micromamba create -r ~/micromamba -n py38 -c conda-forge python=3.8 --yes
          ./bin/micromamba run -r ~/micromamba -n py38 pip install -r src/requirements.txt
          ./bin/micromamba run -r ~/micromamba -n py38 pyinstaller --onefile --noconsole --icon=Assets/PyConvert_Logo.ico src/PyConvert.py

      - name: Set release date
        run: echo "RELEASE_DATE=$(date -u +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_DATE }}
          tag:  ${{ env.RELEASE_DATE }}
          artifacts: "dist/PyConvert"
          token: ${{ secrets.TEST_TOKEN }}
          allowUpdates: true
          draft: true


  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: |
          python -m pip install -r src/requirements.txt
          python -m PyInstaller --onefile --noconsole --icon=Assets/PyConvert_Logo.ico src/PyConvert.py

      - name: Set release date
        shell: bash
        run: echo "RELEASE_DATE=$(date -u +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_DATE }}
          tag:  ${{ env.RELEASE_DATE }}
          artifacts: "dist/PyConvert.exe"
          token: ${{ secrets.TEST_TOKEN }}
          allowUpdates: true
          draft: true
